version: "2"
services:
    brain:
        build: .
        expose:
            - 5000
        command: ~/catkin_ws/devel/env.sh rosrun openag_brain main -D http://db:5984 -H brain
        depends_on:
            - db
    db:
        image: dogi/rpi-couchdb
        expose:
            - 5984
        ports:
            - "5984:5984"
